### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by jerodsanto** [cloudhead/toto#22]
I imported 80 articles from my old blog and after clicking around from the index to an article and back again I get:

```
Errno::EMFILE at / Too many open files
```

It seems you need to find a safe place to call `File#close` after reading in each file's content.

**Comment by cloudhead** [comment]
aha yes, I'll add that to the Article#load method.

**Comment by cloudhead** [comment]
Fixed

http://github.com/cloudhead/toto/commit/6d6339d6a5fa152064ec10f7b30499f5cb824f9b

**Comment by jerodsanto** [comment]
I still get this error with 0.3.2. Let me know if I can give you more information to help figure out where the problem is.

**Comment by cloudhead** [comment]
oh hmmm. Are you on windows? If not, can you try running `ulimit` in the console, see what it returns? You can also set it, with `ulimit -n 10000` to allow more files to be open at once.. I just want to figure out where the problem is.

**Comment by jerodsanto** [comment]
I'm on OS 10.6.2, Ruby 1.8.7, unicorn 0.96.0, toto 0.3.2

When I run `ulimit` it returns `unlimited`. Perhaps you can recreate this bug by creating a test instance with ~ 80 files in the articles directory, firing up unicorn, and clicking around on a few pages.

Here is toto's stack trace:

```
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:155:in `initialize'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:155:in `new'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:155:in `initialize'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:154:in `map'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:154:in `initialize'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:105:in `new'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:105:in `go'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:118:in `[]'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:118:in `go'
/opt/ruby-1.8.7/lib/ruby/gems/1.8/gems/toto-0.3.2/lib/toto.rb:326:in `call'
```

**Comment by cloudhead** [comment]
Ok I think I figured it out, will post a fix shortly.

**Comment by cloudhead** [comment]
This should be fixed in 0.3.3.

**Comment by jerodsanto** [comment]
Looks like it is. Thanks!

**Comment by tadman** [comment]
`ulimit` may say "unlimited" but you must do `ulimit -a` to see the breakdown. The default for open files is often 256, not unlimited.
